<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Http" Version="10.0.0" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.0" />

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AspPresentation\AspPresentation.csproj" />
		<ProjectReference Include="..\Demo.Application\Demo.Application.csproj" />
		<ProjectReference Include="..\Demo.Infrastructure\Demo.Infrastructure.csproj" />
		<ProjectReference Include="..\DotNetWebApiBestPractice.ServiceDefaults\DotNetWebApiBestPractice.ServiceDefaults.csproj" />
		<ProjectReference Include="..\ServiceManagement\ServiceManagement.csproj" />
	</ItemGroup>

</Project>
