<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AspireMigration-25628983-a46f-407f-a052-b4b31cef7bd5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireDefaults\AspireDefaults.csproj" />
    <ProjectReference Include="..\Demo.Infrastructure\Demo.Infrastructure.csproj" />
    <ProjectReference Include="..\DotNetWebApiBestPractice.ServiceDefaults\DotNetWebApiBestPractice.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
