<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DemoDomain\DemoDomain.csproj" />
		<ProjectReference Include="..\..\..\Packages\src\EFInfrastructure\EFInfrastructure.csproj" />
		<ProjectReference Include="..\..\..\Packages\src\ServiceManagement\ServiceManagement.csproj" />
	</ItemGroup>

</Project>
